backend:
  name: git-gateway
  branch: master

media_folder: content
public_folder: content

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "Custom pages other than the main page"
    summary: "{{title}}"
    folder: "content"
    create: true
    slug: "{{slug}}"
    # Netlify CMS doesn't support MDX files right now, so we tell it to treat them as Markdown
    extension: mdx
    format: frontmatter
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Header image"
        name: "image"
        widget: "image"
        required: false
        # Used to disable preview
        tagname: ""
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "settings"
    label: "Settings"
    # Prevent users from deleting documents in this collection
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: data/config.json
        description: "General site settings"
        fields:
          - name: "siteMetadata"
            label: "Site metadata"
            widget: "object"
            fields:
              - name: "author"
                label: "Author"
                widget: "object"
                fields:
                  - name: "name"
                    label: "Name"
                    widget: "string"
                  - name: "twitter"
                    label: "Twitter"
                    widget: "string"
                    required: false
              - name: "contact"
                label: "Contact"
                widget: "object"
                fields:
                  - name: "address"
                    label: "Address"
                    widget: "list"
                    required: false
                    fields:
                      - name: "key"
                        label: "Unique name"
                        widget: "string"
                      - name: "value"
                        label: "Value"
                        widget: "string"
                  - name: "email"
                    label: "Email"
                    widget: "string"
                    required: false
                  - name: "phone"
                    label: "Phone"
                    widget: "string"
                    required: false
                  - name: "socialMedia"
                    label: "Social media links"
                    widget: "object"
                    required: false
                    fields:
                      - name: "gitHub"
                        label: "GitHub"
                        widget: "string"
                        required: false
                      - name: "instagram"
                        label: "Instagram"
                        widget: "string"
                        required: false
              - label: "Global title"
                name: "title"
                widget: "string"
              - name: "description"
                label: "Description"
                widget: "string"
          - name: "sidebar"
            label: "Sidebar items"
            label_singular: "Sidebar item"
            widget: "list"
            fields:
              - name: "content"
                label: "Value"
                widget: "string"
              - name: "href"
                label: "Element ID of target"
                widget: "string"
          - name: "header"
            label: "Navbar items"
            label_singular: "Navbar item"
            widget: "list"
            fields:
              - name: "externalLink"
                label: "External link"
                widget: "boolean"
              - name: "label"
                label: "Label"
                widget: "string"
              - name: "target"
                label: "Link"
                widget: "string"
