name: Node.js CI

on: push

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: "Git checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Yarn
        run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - name: Install
        run: yarn install
        env:
          GATSBY_TELEMETRY_DISABLED: 1
      - name: Lint JavaScript
        run: yarn run lint
      - name: Check formatting
        run: yarn run check-fmt
      - name: Build for production
        run: yarn run build
        env:
          GATSBY_TELEMETRY_DISABLED: 1
